=== kwakeroni/etui/src/main/resources/com/quaxantis/etui/tag/tag-collection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="https://quaxantis.com/etui/tags"
           xmlns="https://quaxantis.com/etui/tags"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tag-collection" type="TagCollection"/>
    <xs:complexType name="Family">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="homePage" type="xs:string" minOccurs="0"/>
            <xs:element name="reference" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="tags" type="Tags" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="group" type="xs:string" use="required"/>
        <xs:attribute name="readonly" type="xs:boolean" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Default readonly setting for tags in this family.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TagCollection">
        <xs:sequence>
            <xs:element name="collection" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="family" type="Family" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Tag">
        <xs:sequence>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="format" type="Format" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="readonly" type="xs:boolean" use="optional" />
        <xs:attribute name="group" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Overrides the group of the family.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="Tags">
        <xs:sequence>
            <xs:element name="tag" type="Tag" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Format">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0">
            </xs:element>
            <xs:element name="examples" type="Examples" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>date/time according to ISO 8601-1</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Example">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="pattern" use="optional"/>
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="Examples">
        <xs:sequence>
            <xs:element type="Example" name="example" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>date according to ISO 8601-1 month and year (YYYY-MM) just year (YYYY) Date ranges
                        may be specified using ISO 8601 period of time specification in which start and end dates are
                        separated by a '/' (slash) character. Date ranges may be specified using ISO 8601 period of time
                        specification in which start and end dates are separated by a '/' (slash) character. Date ranges
                        may be specified using ISO 8601 period of time specification in which start and end dates are
                        separated by a '/' (slash) character. date/time according to ISO 8601-1
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kwakeroni/etui/src/main/resources/com/quaxantis/etui/tag/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-collection xmlns="https://quaxantis.com/etui/tags" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://quaxantis.com/etui/tags tag-collection.xsd">
    <collection>System</collection>
    <family name="sourcefile" group="" readonly="true">
        <label>Source File attribute</label>
        <tags>
            <tag name="SourceFile" />
        </tags>
    </family>
    <family name="exiftool" group="ExifTool" readonly="true">
        <label>Exiftool information</label>
        <reference>https://exiftool.org/TagNames/Extra.html</reference>
        <tags>
            <tag name="ExifToolVersion" />
        </tags>
    </family>
    <family name="file" group="File" readonly="true">
        <label>File attributes</label>
        <reference>https://exiftool.org/TagNames/Extra.html</reference>
        <description>
            Represents some system attributes of the file.
        </description>
        <tags>
            <tag name="FileName" />
            <tag name="Directory" />
            <tag name="FileSize" />
            <tag name="FileModifyDate" />
            <tag name="FileAccessDate" />
            <tag name="FileCreateDate" />
            <tag name="FilePermissions" />
            <tag name="FileType" />
            <tag name="FileTypeExtension" />
            <tag name="MIMEType" />
        </tags>
    </family>
    <family name="composite" group="Composite" readonly="true">
        <label>Composite derived attributes</label>
        <reference>https://exiftool.org/TagNames/Composite.html</reference>
        <description>The values of the composite tags are Derived From the values of other tags.</description>
        <tags>
            <tag name="ImageSize" />
            <tag name="ImageWidth" />
            <tag name="ImageHeight" />
            <tag name="Megapixels" />
        </tags>
    </family>
    <family name="icc_profile" group="ICC_Profile" readonly="true">
        <description>
            ICC profile information is used in many different file types including
            JPEG, TIFF, PDF, PostScript, Photoshop, PNG, MIFF, PICT, QuickTime, XCF and some RAW formats.
            While the tags listed below are not individually writable, the entire profile itself can be accessed via the extra 'ICC_Profile' tag,
            but this tag is neither extracted nor written unless specified explicitly.
        </description>
    </family>
</tag-collection>

=== kwakeroni/etui/src/main/resources/com/quaxantis/etui/tag/formats.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-collection xmlns="https://quaxantis.com/etui/tags" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://quaxantis.com/etui/tags tag-collection.xsd">
    <collection>Formats</collection>
    <family name="gif" group="GIF" readonly="true">
        <label>GIF</label>
        <reference>https://www.w3.org/Graphics/GIF/spec-gif89a.txt</reference>
        <description>
            Information extracted from GIF images.
        </description>
        <tags>
            <tag name="Comment" readonly="false" group="File" />
            <tag name="Duration" />
            <tag name="FrameCount" />
            <tag name="GIFVersion" />
            <tag name="Text" />
            <tag name="TransparentColor" />
            <tag name="MIDIControlVersion" />
            <tag name="SequenceNumber" />
            <tag name="MelodicPolyphony" />
            <tag name="PercussivePolyphony" />
            <tag name="ChannelUsage" />
            <tag name="DelayTime" />
            <tag name="AnimationIterations" />
            <tag name="ImageWidth" />
            <tag name="ImageHeight" />
            <tag name="HasColorMap" />
            <tag name="ColorResolutionDepth" />
            <tag name="BitsPerPixel" />
            <tag name="BackgroundColor" />
            <tag name="PixelAspectRatio" />
        </tags>
    </family>
    <family name="png" group="PNG">
        <label>PNG</label>
        <reference>http://www.libpng.org/pub/png/spec/1.2/</reference>
        <description>
            Tags extracted from PNG images.
        </description>
        <tags>
            <tag name="ImageWidth" readonly="true" />
            <tag name="ImageHeight" readonly="true" />
            <tag name="BitDepth" readonly="true" />
            <tag name="ColorType" readonly="true">
                <description>
                    0 = Grayscale
                    2 = RGB
                    3 = Palette
                    4 = Grayscale with Alpha
                    6 = RGB with Alpha
                </description>
            </tag>
            <tag name="Compression" readonly="true">
                <description>0 = Deflate/Inflate</description>
            </tag>
            <tag name="Filter" readonly="true">
                <description>0 = Adaptive</description>
            </tag>
            <tag name="Interlace" readonly="true">
                <description>
                    0 = Noninterlaced
                    1 = Adam7 Interlace
                </description>
            </tag>
            <tag name="PixelsPerUnitX" readonly="true" />
            <tag name="PixelsPerUnitY" readonly="true" />
            <tag name="PixelUnits" readonly="true" />
            <tag name="Artist" />
            <tag name="Author" />
            <tag name="Collection" />
            <tag name="Comment" />
            <tag name="Copyright" />
            <tag name="CreationTime" />
            <tag name="Description" />
            <tag name="Disclaimer" />
            <tag name="Document" />
            <tag name="Label" />
            <tag name="Make" />
            <tag name="Model" />
            <tag name="Software" />
            <tag name="Source" />
            <tag name="TimeStamp" />
            <tag name="Title" />
            <tag name="URL" />
            <tag name="PNGWarning" />
            <tag name="AestheticScore" />
            <tag name="CreateDate" />
            <tag name="ModDate" />
            <tag name="Parameters" />


            <tag name="FileName" readonly="true" />
            <tag name="Directory" readonly="true" />
            <tag name="FileSize" readonly="true" />
            <tag name="FileModifyDate" readonly="true" />
            <tag name="FileAccessDate" readonly="true" />
            <tag name="FileCreateDate" readonly="true" />
            <tag name="FilePermissions" readonly="true" />
            <tag name="FileType" readonly="true" />
            <tag name="FileTypeExtension" readonly="true" />
            <tag name="MIMEType" readonly="true" />
        </tags>
    </family>
    <family name="webp" group="RIFF" readonly="true">
        <label>WEBP</label>
        <tags>
            <tag name="AlphaPreprocessing" />
            <tag name="AlphaFiltering" />
            <tag name="AlphaCompression" />
            <tag name="BackgroundColor" />
            <tag name="AnimationLoopCount" />
            <tag name="Duration" />
            <tag name="VP8Version" />
            <tag name="ImageWidth" />
            <tag name="HorizontalScale" />
            <tag name="ImageHeight" />
            <tag name="VerticalScale" />
            <tag name="AlphaIsUsed" />
            <tag name="WebP_Flags" />
        </tags>
    </family>
    <family name="pdf" group="PDF">
        <label>PDF</label>
        <description>
            Tags extracted from PDF documents.
        </description>
        <!-- Note
             Custom tags can be added to the .ExifTool_config:
             ```
                %Image::ExifTool::UserDefined = (
                    'Image::ExifTool::PDF::Info' => {
                        MyTag => { },
                    },
                );
                1; # end
            ```
            The PDF:MyTag tag will then be visible in the Personalized section from Acrobat Reader.
         -->
        <tags>
            <tag name="PDFVersion" readonly="true" />
            <tag name="PageCount" readonly="true" />
            <tag name="PageLayout" readonly="true" />
            <tag name="PageMode" readonly="true" />
            <tag name="Language" readonly="true" />
            <tag name="Title" />
            <tag name="Author" />
            <tag name="Subject" />
            <tag name="Keywords" />
            <tag name="CreateDate" />
            <tag name="ModifyDate" />
            <tag name="SourceModified" />
            <tag name="Trapped" readonly="true"/>
            <tag name="Creator">
                <label>Creator Application</label>
                <description>Software application used to create the PDF</description>
            </tag>
            <tag name="Producer">
                <label>PDF Producer</label>
                <description>Software library that produced the PDF</description>
            </tag>
        </tags>
    </family>
</tag-collection>

=== kwakeroni/etui/src/main/resources/com/quaxantis/etui/tag/iptc-ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-collection xmlns="https://quaxantis.com/etui/tags" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://quaxantis.com/etui/tags tag-collection.xsd">
    <collection>Standards</collection>
    <family name="iptcExt" group="XMP">
        <label>IPTC Extension</label>
        <homePage>https://iptc.org/standards/photo-metadata/iptc-standard/</homePage>
        <reference>
            https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#iptc-extension-schema-1-8-specifications
        </reference>
        <description>
            The IPTC Photo Metadata Standard is the most widely used standard to describe photos, because of its
            universal acceptance
            among news agencies, photographers, photo agencies, libraries, museums, and other related industries.
            It structures and defines metadata properties that allow users to add precise and reliable data about
            images.

            Today, the IPTC Photo Metadata Standard consists of two schemas – IPTC Core and IPTC Extension –
            which were built on the legacy of the original IPTC-IIM,
            and developed by the IPTC for professional use with a focus on news and stock photos.
            IPTC worked alongside Adobe on the technical implementation of the metadata that employs Adobe’s XMP
            technology
            (now an ISO Standard)as an enriched alternative to the IIM format.

            IPTC Core and IPTC Extension define metadata properties with comprehensive sets of fields
            that allow users to add precise and reliable data about people, locations, and products shown in an image.
            It also supports dates, names and identifiers regarding the creation of the photo,
            and a flexible way to express rights information.

            This list provides a subset of the IPTC Extension metadata specification.
        </description>
        <tags>
            <tag name="PersonInImage">
                <label>Person shown</label>
                <description>Name of a person shown in the image.</description>
                <format>
                    <description>Data type: Text / Cardinality: 0..unbounded</description>
                </format>
            </tag>
            <tag name="PersonInImageName">
                <label>Person shown (Name)</label>
                <description>Name of the person shown in the image.</description>
                <format>
                    <description>Data type: Text / Cardinality: 0..1</description>
                </format>
            </tag>
            <tag name="PersonInImageId">
                <label>Person shown (ID)</label>
                <description>Globally Unique Identifier of the person shown in the image, such as those from WikiData or
                    Freebase
                </description>
                <format>
                    <description>
                        This should be an identifier as it is used with semantic web technology.
                        Data type: URI / Cardinality: 0..unbounded
                    </description>
                </format>
            </tag>
        </tags>
    </family>
</tag-collection>

=== kwakeroni/etui/src/main/resources/com/quaxantis/etui/tag/creative-commons.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-collection xmlns="https://quaxantis.com/etui/tags" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://quaxantis.com/etui/tags tag-collection.xsd">
    <collection>Standards</collection>
    <family name="cc" group="XMP">
        <label>Creative Commons</label>
        <homePage>https://wiki.creativecommons.org/wiki/XMP</homePage>
        <reference>https://creativecommons.org/ns#</reference>
        <description>
            Creative Commons is a global nonprofit organization that enables sharing and reuse
            of creativity and knowledge through the provision of free legal tools.
            Creative Commons licenses provide an easy way to manage the copyright terms
            that attach automatically to all creative material under copyright.
            These licenses allow that material to be shared and reused under terms that are flexible and legally sound.
            All of these licenses require that users provide attribution to the creator when the material is used and shared.
        </description>
        <tags>
            <tag name="license">
                <label>License</label>
                <description>A Work has a License. (a subproperty of dcterms:license, the same as xhtml:license)</description>
                <format>
                    <description>
                        The license URL.

                        Aspects:

                        BY: credit must be given to the creator.

                        SA: Adaptations must be shared under the same terms.

                        NC: Only noncommercial uses of the work are permitted.

                        ND: No derivatives or adaptations of the work are permitted.

                        CC0: Public Domain
                    </description>
                    <examples>
                        <example value="https://creativecommons.org/licenses/by/4.0/"/>
                        <example value="https://creativecommons.org/licenses/by-sa/4.0/"/>
                        <example value="https://creativecommons.org/licenses/by-nc/4.0/"/>
                        <example value="https://creativecommons.org/licenses/by-nc-sa/4.0/"/>
                        <example value="https://creativecommons.org/licenses/by-nc-nd/4.0/"/>
                        <example value="https://creativecommons.org/publicdomain/zero/1.0/"/>
                    </examples>
                </format>
            </tag>
            <tag name="attributionName">
                <label>Attribution Name</label>
                <description>The name the creator of a Work would like used when attributing re-use.</description>
            </tag>
            <tag name="attributionURL">
                <label>Attribution URL</label>
                <description>The URL the creator of a Work would like used when attributing re-use.</description>
            </tag>
            <tag name="morePermissions">
                <label>More Permissions</label>
                <description>A related resource which describes additional permissions or alternative licenses for a Work which may be available.</description>
                <format>
                    <description>
                        A URL where additional permissions (commercial licensing, etc) are available.
                    </description>
                </format>
            </tag>
            <tag name="useGuidelines">
                <label>Use Guidelines</label>
                <description>A related resource which defines non-binding use guidelines for the work .</description>
            </tag>
        </tags>
    </family>
</tag-collection>
